### ISSUE TITLE
Friendly error message upon user accidentally invoke `Docker build` upon `blimp up`

### ISSUE THREAD

**Issue by rizdaprasetya** [kelda/blimp#35]
Nice product you have here 👍 . Here is some feedback from my personal use:

**Is your feature request related to a problem? Please describe.**
When user accidentally include `build` command on `docker-compose.yml` e.g. step to reproduce:

1. Clone the official example `git clone https://github.com/kelda/node-todo && cd node-todo`
2. Edit `docker-compose.yml`, include a `build` command, like this:
```yml
version: '3'
services:
  web:
    # for example I accidentally include build command here:
    build: .
    entrypoint:
      - "/usr/src/app/node_modules/.bin/nodemon"
      - "/usr/src/app/server.js"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - "./app:/usr/src/app/app"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

```
3. save the file
4. run `blimp up`

User will get the following error message which might not be descriptive enough for user to fix the issue:
```
➜  node-todo git:(master) ✗ blimp up
Booting cloud sandbox
Building image for web:
[Error] Get help at https://kelda.io/blimp/docs/help/
build web: start build: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Describe the solution you'd like**
- Catch that error message, and tell user to not avoid docker `build` command in the `docker-compose.yml` file.
OR
- read the `docker-compose.yml` file and if `build` command is detected, refuse to run and display proper err msg.

or maybe somekind of messaging `looks like you are trying to invoke Docker 'build' command, this command is not currently supported in Blimp's cloud container. Please check your 'docker-compose.yml' file and remove the 'build' command`.

**Additional context**
User can easily accidentally include `build` command within `docker-compose.yml` because they think **Blimp** is ready-to-use drop-in-replacement for **Docker Compose** (as you describe it). And lots of users are having `build` command within their `docker-compose.yml`.

If they run `blimp up` and it didn't work, they may think your product is broken or not working as described. They may drop off. So this will be good improvement for new user who might not understand anything of your product. 

Well it took me a while to figure out what went wrong too.
