### ISSUE TITLE
Add support for `docker-compose run`

### ISSUE THREAD

**Issue by Laski** [kelda/blimp#52]
**Is your feature request related to a problem? Please describe.**
We have many environment initialization routines implemented inside the docker image and run with compose (e.g. `docker-compose run backend load_db`). In order to completely replace `docker-compose` with `blimp`, it would be nice that `blimp` supports that syntax and behaviour.

**Describe the solution you'd like**
Be able to `blimp run backend load_db` (with or without support for [the other parameters](https://docs.docker.com/compose/reference/run/)).

**Additional context**
```
$ blimp run backend load_db
unknown command "run" for "blimp"

Did you mean this?
	up
```

PS: I just found this project and looks really promising. Thanks!

**Comment by kklin** [comment]
Hi @Laski! We don't expect to add `blimp run` soon unfortunately since we're not working on it full time anymore.

However, we have had some teams simulate `docker-compose run` with `blimp exec`. The basic pattern is to create a dummy version of the container for blimp to boot, and then exec into it to run commands.

E.g.

```
services:
  backend:
    image: backend-image
    # This makes it so the container starts, making it available for `blimp exec`, but its command just makes it wait forever.
    command: tail -f /dev/null
```

Then once you `blimp up`, you can run `blimp exec backend load_db`.

Hope that helps!
